eureka:
  client:
    service-url:
      defaultZone: http://prayer:123456@prayer1.com:8761/eureka/
server:
  port: 8760
spring:
  application:
    name: service-consumer

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1