spring:
  application:
    name: feign-caller

eureka:
  client:
    service-url:
      defaultZone: http://prayer:123456@prayer1.com:8761/eureka/
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
    # 将自己真正的健康状态传播到server。添加这个配置后，需要引入actuator包，并实现HealthIndicator接口
    healthcheck:
      enabled: true
  instance:
    #续约发送间隔默认30秒，心跳间隔
    lease-renewal-interval-in-seconds: 5
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 60


server:
  port: 8765

service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数

#开启debug模式
debug: true
logging:
  level:
    com.prayerlaputa.feign.ServiceMy: debug
